# shellcheck shell=bash
# Render rule fragments and the playbook routing index in manifest order.

_AGENT_RULES_RENDERED_BODY=''

_agent_rules_playbook_index() {
  local index='' i line
  for i in "${!_AGENT_RULES_PLAYBOOK_ROUTES[@]}"; do
    line="- ${_AGENT_RULES_PLAYBOOK_TRIGGERS[$i]}: \`${_AGENT_RULES_PLAYBOOK_ROUTES[$i]}\`"
    if [[ -n "$index" ]]; then
      index+=$'\n'"$line"
    else
      index="$line"
    fi
  done
  REPLY="$index"
}

_agent_rules_expand_rule() {
  local content="$1" line output='' first=1
  _agent_rules_playbook_index
  local index="$REPLY"
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      '<!-- agent-rules-playbook-index -->' | '<!-- dot-playbook-index -->')
        line="$index"
        ;;
    esac
    if ((first)); then
      output="$line"
      first=0
    else
      output+=$'\n'"$line"
    fi
  done <<<"$content"
  REPLY="$output"
}

_agent_rules_render() {
  local body fragment content first=1
  body=$'# Generated by agent-rules. Do not edit this block directly.\n# Edit the source fragments selected by the manifest and rerun the orchestrator.'
  for content in "${_AGENT_RULES_RULE_CONTENTS[@]+"${_AGENT_RULES_RULE_CONTENTS[@]}"}"; do
    _agent_rules_expand_rule "$content" || return 1
    fragment="$REPLY"
    [[ -n "$fragment" ]] || continue
    if ((first)); then
      body+=$'\n\n'"$fragment"
      first=0
    else
      body+=$'\n\n'"$fragment"
    fi
  done
  body=$(printf '%s\n' "$body" |
    sed '/^#[[:space:]]*vim:/d; /^#[[:space:]]*-\*-/d')
  _AGENT_RULES_RENDERED_BODY="$body"
}
