# shellcheck shell=bash
# Conservative managed-block replacement that preserves unrelated target text.

_AGENT_RULES_MARKER='# agent-rules-sync:aggregate'
_AGENT_RULES_LEGACY_MARKER_PREFIX='# dot-managed:agent-rules:'

_agent_rules_is_begin_marker() {
  case "$1" in
    "$_AGENT_RULES_MARKER begin" | "$_AGENT_RULES_LEGACY_MARKER_PREFIX"*' begin') return 0 ;;
    *) return 1 ;;
  esac
}

_agent_rules_is_end_marker() {
  case "$1" in
    "$_AGENT_RULES_MARKER end" | "$_AGENT_RULES_LEGACY_MARKER_PREFIX"*' end') return 0 ;;
    *) return 1 ;;
  esac
}

_agent_rules_append_line() {
  local current="$1" line="$2"
  if [[ -n "$current" ]]; then
    REPLY="$current"$'\n'"$line"
  else
    REPLY="$line"
  fi
}

_agent_rules_strip_managed() {
  local input="$1" line output='' expected_end='' in_block=0 found=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if _agent_rules_is_begin_marker "$line"; then
      if ((in_block)); then
        return 1
      fi
      in_block=1
      found=1
      expected_end="${line% begin} end"
      continue
    fi
    if _agent_rules_is_end_marker "$line"; then
      if ((in_block == 0)) || [[ "$line" != "$expected_end" ]]; then
        return 1
      fi
      in_block=0
      expected_end=''
      continue
    fi
    if ((in_block == 0)); then
      _agent_rules_append_line "$output" "$line"
      output="$REPLY"
    fi
  done <<<"$input"
  ((in_block == 0)) || return 1
  REPLY="$output"
  REPLY_FOUND="$found"
}

_agent_rules_trim_outer_space() {
  local text="$1" char

  # Avoid locale-sensitive glob tricks here. This text can contain arbitrary
  # user-authored Markdown, while the only separators emitted by the provider
  # are the six ASCII whitespace bytes recognized by POSIX `[:space:]`.
  while [[ -n "$text" ]]; do
    char=${text:0:1}
    case "$char" in
      ' ' | $'\t' | $'\n' | $'\r' | $'\v' | $'\f') text=${text:1} ;;
      *) break ;;
    esac
  done
  while [[ -n "$text" ]]; do
    char=${text: -1}
    case "$char" in
      ' ' | $'\t' | $'\n' | $'\r' | $'\v' | $'\f') text=${text:0:${#text}-1} ;;
      *) break ;;
    esac
  done
  REPLY="$text"
}

_agent_rules_normalize_unmanaged() {
  local text="$1" line output='' previous_empty=0

  # GNU and BusyBox do not provide a uniform `cat -s` contract. Implement the
  # one behavior needed here directly: preserve every nonempty line and reduce
  # each run of truly empty lines to one. This keeps unmanaged user text intact
  # on every supported platform.
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ -z "$line" ]]; then
      ((previous_empty)) && continue
      previous_empty=1
    else
      previous_empty=0
    fi
    _agent_rules_append_line "$output" "$line"
    output="$REPLY"
  done <<<"$text"

  _agent_rules_trim_outer_space "$output"
}

_agent_rules_managed_block() {
  local body="$_AGENT_RULES_RENDERED_BODY"
  _agent_rules_trim_outer_space "$body"
  body="$REPLY"
  printf '%s\n%s\n%s\n%s\n%s' \
    "$_AGENT_RULES_MARKER begin" \
    '# DO NOT EDIT: generated by agent-rules-sync' \
    "# manifest: $_AGENT_RULES_MANIFEST_FILE" \
    "$body" \
    "$_AGENT_RULES_MARKER end"
}

_agent_rules_prepare_target_parent() {
  local target="$1" parent
  parent=${target%/*}
  [[ "$parent" != "$target" ]] || parent=.
  if [[ ! -d "$parent" ]]; then
    mkdir -p -- "$parent" || return 1
    chmod 700 "$parent" || return 1
  fi
}

_agent_rules_write_private_file() {
  local target="$1" text="$2" tmp
  if [[ -f "$target" ]] && printf '%s' "$text" | cmp -s - "$target"; then
    chmod 600 "$target" || return 1
    return 0
  fi
  _agent_rules_prepare_target_parent "$target" || return 1
  _agent_rules_sibling_tmp_for "$target" || return 1
  tmp="$REPLY"
  printf '%s' "$text" >"$tmp" || return 1
  chmod 600 "$tmp" || return 1
  _agent_rules_publish_tmp "$tmp" "$target"
}

_agent_rules_publish_target() {
  local target="$1" block="$2" current='' rest result
  if [[ -e "$target" && ! -f "$target" ]]; then
    _agent_rules_error "target is not a regular file: $target"
    return 1
  fi
  [[ -f "$target" ]] && current=$(<"$target")
  if ! _agent_rules_strip_managed "$current"; then
    _agent_rules_error "malformed managed block in target: $target"
    return 1
  fi
  rest="$REPLY"
  _agent_rules_normalize_unmanaged "$rest"
  rest="$REPLY"
  if [[ -n "$rest" ]]; then
    result="$rest"$'\n\n'"$block"$'\n'
  else
    result="$block"$'\n'
  fi
  _agent_rules_write_private_file "$target" "$result" || {
    _agent_rules_error "could not publish target: $target"
    return 1
  }
}

_agent_rules_prune_target() {
  local target="$1" current rest found
  [[ -e "$target" || -L "$target" ]] || return 0
  if [[ ! -f "$target" ]]; then
    _agent_rules_error "refusing to prune non-file target: $target"
    return 1
  fi
  current=$(<"$target")
  if ! _agent_rules_strip_managed "$current"; then
    _agent_rules_error "malformed managed block in target: $target"
    return 1
  fi
  rest="$REPLY"
  found="$REPLY_FOUND"
  ((found)) || return 0
  _agent_rules_normalize_unmanaged "$rest"
  rest="$REPLY"
  if [[ -n "$rest" ]]; then
    _agent_rules_write_private_file "$target" "$rest"$'\n' || return 1
  else
    rm -f -- "$target" || return 1
  fi
}
