# shellcheck shell=bash
# Conservative managed-block replacement that preserves unrelated target text.

_AGENT_RULES_MARKER='# agent-rules-sync:aggregate'
_AGENT_RULES_LEGACY_MARKER_PREFIX='# dot-managed:agent-rules:'
# Published targets carry generated policy that may quote private rule prose,
# so publication and `check` share this one octal mode.
_AGENT_RULES_TARGET_MODE=600
# The third line of every published block names the manifest it came from.
# It is provenance for humans, so `check` compares it by position, not path.
_AGENT_RULES_MANIFEST_HEADER='# manifest: '

_agent_rules_is_begin_marker() {
  case "$1" in
    "$_AGENT_RULES_MARKER begin" | "$_AGENT_RULES_LEGACY_MARKER_PREFIX"*' begin') return 0 ;;
    *) return 1 ;;
  esac
}

_agent_rules_is_end_marker() {
  case "$1" in
    "$_AGENT_RULES_MARKER end" | "$_AGENT_RULES_LEGACY_MARKER_PREFIX"*' end') return 0 ;;
    *) return 1 ;;
  esac
}

_agent_rules_append_line() {
  local current="$1" line="$2"
  if [[ -n "$current" ]]; then
    REPLY="$current"$'\n'"$line"
  else
    REPLY="$line"
  fi
}

_agent_rules_strip_managed() {
  local input="$1" line output='' expected_end='' in_block=0 found=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if _agent_rules_is_begin_marker "$line"; then
      if ((in_block)); then
        return 1
      fi
      in_block=1
      found=1
      expected_end="${line% begin} end"
      continue
    fi
    if _agent_rules_is_end_marker "$line"; then
      if ((in_block == 0)) || [[ "$line" != "$expected_end" ]]; then
        return 1
      fi
      in_block=0
      expected_end=''
      continue
    fi
    if ((in_block == 0)); then
      _agent_rules_append_line "$output" "$line"
      output="$REPLY"
    fi
  done <<<"$input"
  ((in_block == 0)) || return 1
  REPLY="$output"
  REPLY_FOUND="$found"
}

_agent_rules_trim_outer_space() {
  local text="$1" char

  # Avoid locale-sensitive glob tricks here. This text can contain arbitrary
  # user-authored Markdown, while the only separators emitted by the provider
  # are the six ASCII whitespace bytes recognized by POSIX `[:space:]`.
  while [[ -n "$text" ]]; do
    char=${text:0:1}
    case "$char" in
      ' ' | $'\t' | $'\n' | $'\r' | $'\v' | $'\f') text=${text:1} ;;
      *) break ;;
    esac
  done
  while [[ -n "$text" ]]; do
    char=${text: -1}
    case "$char" in
      ' ' | $'\t' | $'\n' | $'\r' | $'\v' | $'\f') text=${text:0:${#text}-1} ;;
      *) break ;;
    esac
  done
  REPLY="$text"
}

_agent_rules_normalize_unmanaged() {
  local text="$1" line output='' previous_empty=0

  # GNU and BusyBox do not provide a uniform `cat -s` contract. Implement the
  # one behavior needed here directly: preserve every nonempty line and reduce
  # each run of truly empty lines to one. This keeps unmanaged user text intact
  # on every supported platform.
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ -z "$line" ]]; then
      ((previous_empty)) && continue
      previous_empty=1
    else
      previous_empty=0
    fi
    _agent_rules_append_line "$output" "$line"
    output="$REPLY"
  done <<<"$text"

  _agent_rules_trim_outer_space "$output"
}

_agent_rules_managed_block() {
  local body="$_AGENT_RULES_RENDERED_BODY"
  _agent_rules_trim_outer_space "$body"
  body="$REPLY"
  printf '%s\n%s\n%s\n%s\n%s' \
    "$_AGENT_RULES_MARKER begin" \
    '# DO NOT EDIT: generated by agent-rules-sync' \
    "$_AGENT_RULES_MANIFEST_HEADER$_AGENT_RULES_MANIFEST_FILE" \
    "$body" \
    "$_AGENT_RULES_MARKER end"
}

_agent_rules_prepare_target_parent() {
  local target="$1" parent
  parent=${target%/*}
  [[ "$parent" != "$target" ]] || parent=.
  if [[ ! -d "$parent" ]]; then
    mkdir -p -- "$parent" || return 1
    chmod 700 "$parent" || return 1
  fi
}

_agent_rules_write_private_file() {
  local target="$1" text="$2" tmp
  if [[ -f "$target" ]] && printf '%s' "$text" | cmp -s - "$target"; then
    chmod "$_AGENT_RULES_TARGET_MODE" "$target" || return 1
    return 0
  fi
  _agent_rules_prepare_target_parent "$target" || return 1
  _agent_rules_sibling_tmp_for "$target" || return 1
  tmp="$REPLY"
  printf '%s' "$text" >"$tmp" || return 1
  chmod "$_AGENT_RULES_TARGET_MODE" "$tmp" || return 1
  _agent_rules_publish_tmp "$tmp" "$target"
}

_agent_rules_publish_target() {
  local target="$1" block="$2" current='' rest result
  if [[ -e "$target" && ! -f "$target" ]]; then
    _agent_rules_error "target is not a regular file: $target"
    return 1
  fi
  # A failed read must not look like an empty file: publishing would then
  # replace the owner's unmanaged prose with only the generated block.
  if [[ -f "$target" ]] && ! current=$(<"$target"); then
    _agent_rules_error "cannot read target: $target"
    return 1
  fi
  if ! _agent_rules_strip_managed "$current"; then
    _agent_rules_error "malformed managed block in target: $target"
    return 1
  fi
  rest="$REPLY"
  _agent_rules_normalize_unmanaged "$rest"
  rest="$REPLY"
  if [[ -n "$rest" ]]; then
    result="$rest"$'\n\n'"$block"$'\n'
  else
    result="$block"$'\n'
  fi
  _agent_rules_write_private_file "$target" "$result" || {
    _agent_rules_error "could not publish target: $target"
    return 1
  }
}

_agent_rules_prune_target() {
  local target="$1" current rest found
  [[ -e "$target" || -L "$target" ]] || return 0
  if [[ ! -f "$target" ]]; then
    _agent_rules_error "refusing to prune non-file target: $target"
    return 1
  fi
  # Likewise, an unreadable target would otherwise look block-free and be
  # skipped silently, leaving generated policy behind after uninstall.
  current=$(<"$target") || {
    _agent_rules_error "cannot read target: $target"
    return 1
  }
  if ! _agent_rules_strip_managed "$current"; then
    _agent_rules_error "malformed managed block in target: $target"
    return 1
  fi
  rest="$REPLY"
  found="$REPLY_FOUND"
  ((found)) || return 0
  _agent_rules_normalize_unmanaged "$rest"
  rest="$REPLY"
  if [[ -n "$rest" ]]; then
    _agent_rules_write_private_file "$target" "$rest"$'\n' || return 1
  else
    rm -f -- "$target" || return 1
  fi
}

# Print a file's permission bits in octal. GNU, BusyBox, and Termux accept
# `stat -c`; macOS and the BSDs need `-f`. Probing in that order keeps one
# portable helper instead of platform branches at every caller. `-L` follows
# a symlinked target to the file whose mode sync's chmod actually repairs.
_agent_rules_file_mode() {
  stat -L -c '%a' "$1" 2>/dev/null || stat -L -f '%Lp' "$1" 2>/dev/null
}

# Classify one selected destination against what a sync with the current
# manifest would leave there, without modifying it. An empty expected block
# means the manifest selects no rules, so sync would prune instead of publish.
#
# Only provider-owned text is significant. Publication preserves unmanaged
# prose and normalizes its spacing, so neither that prose nor the block's
# position can make a target look stale. Every managed block, including a
# retired dot-managed one, is collected into the comparison, so a second or
# leftover block is drift because the next sync would remove it. The
# manifest header is compared by position only: the same manifest reached
# through another spelling (a symlinked or differently written state path)
# publishes identical policy, so a path difference alone is not drift.
#
# REPLY is one of the stable `check` states documented in the README. Returns
# 1 only when the target cannot be inspected at all.
_agent_rules_target_state() {
  local target="$1" block="$2" current line managed='' blocks=0 in_block=0
  local block_line=0 mode

  if [[ ! -e "$target" ]]; then
    # Publication replaces a dangling symlink like a missing file, while
    # pruning refuses anything that is not a regular file.
    if [[ -z "$block" && -L "$target" ]]; then
      REPLY=not-file
    elif [[ -z "$block" ]]; then
      REPLY=current
    else
      REPLY=missing
    fi
    return 0
  fi
  if [[ ! -f "$target" ]]; then
    REPLY=not-file
    return 0
  fi
  if [[ ! -r "$target" ]]; then
    _agent_rules_error "cannot read target: $target"
    return 1
  fi
  current=$(<"$target")
  if ! _agent_rules_strip_managed "$current"; then
    REPLY=malformed
    return 0
  fi

  # The strip above already proved every block is balanced and correctly
  # terminated, so this pass only needs to collect provider-owned lines.
  while IFS= read -r line || [[ -n "$line" ]]; do
    if _agent_rules_is_begin_marker "$line"; then
      in_block=1
      block_line=0
      blocks=$((blocks + 1))
    fi
    if ((in_block)); then
      block_line=$((block_line + 1))
      # Line 3 follows the begin marker and the DO NOT EDIT line written by
      # _agent_rules_managed_block. Any other position or text still counts.
      if ((block_line == 3)) && [[ "$line" == "$_AGENT_RULES_MANIFEST_HEADER"* ]]; then
        line="$_AGENT_RULES_MANIFEST_HEADER$_AGENT_RULES_MANIFEST_FILE"
      fi
      _agent_rules_append_line "$managed" "$line"
      managed="$REPLY"
    fi
    _agent_rules_is_end_marker "$line" && in_block=0
  done <<<"$current"

  if [[ -z "$block" ]]; then
    if ((blocks == 0)); then
      REPLY=current
    else
      REPLY=stale
    fi
    return 0
  fi
  if ((blocks == 0)); then
    REPLY=unmanaged
    return 0
  fi
  if [[ "$managed" != "$block" ]]; then
    REPLY=stale
    return 0
  fi
  mode=$(_agent_rules_file_mode "$target") || {
    _agent_rules_error "cannot read target mode: $target"
    return 1
  }
  if [[ "$mode" != "$_AGENT_RULES_TARGET_MODE" ]]; then
    REPLY=mode
    return 0
  fi
  REPLY=current
}
